# Generated by Django 5.0.6 on 2024-06-26 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessCode', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EconnectorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connectorType', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElectricRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricRange', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ElectricVehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleType', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('postalCode', models.IntegerField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=256)),
                ('county', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleMake', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='EvChargingStations',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('stationName', models.CharField(max_length=256)),
                ('stationAddress', models.CharField(max_length=256)),
                ('stationPhone', models.CharField(blank=True, max_length=256, null=True)),
                ('stationLocation', models.IntegerField()),
                ('accessCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.accesscode')),
                ('connectorType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.econnectortype')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleLocationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regLocation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='api.location')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleModel', models.CharField(max_length=256)),
                ('modelYear', models.IntegerField()),
                ('access', models.IntegerField(default=0)),
                ('electricRange', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.electricrange')),
                ('regLocation', models.ManyToManyField(through='api.VehicleLocationLink', to='api.location')),
                ('vehicleMake', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.vehiclemake')),
                ('vehicleType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.electricvehicletype')),
            ],
            options={
                'unique_together': {('vehicleModel', 'modelYear', 'vehicleMake', 'electricRange', 'vehicleType')},
            },
        ),
        migrations.AddField(
            model_name='vehiclelocationlink',
            name='vehicleModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.vehiclemodel'),
        ),
    ]
