# Generated by Django 5.0.6 on 2024-06-30 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclelocationlink',
            name='regLocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.location'),
        ),
    ]
